name: Kwiki-DatedAnnounce
version: 0.01
abstract: Date sensitive display of blocks in wiki pages
author: Chris Dent <cdent@burningchrome.com>
license: perl
distribution_type: module
requires:
  Kwiki: 0.37
  Kwiki::Test: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
